microsoft/SharePointDSC.Reverse

- SharePointDSC.Reverse.ps1
- SPServiceinstance now in ConfigurationData.psd1
- Multi-Server node now dynamically generating MOF from ConfigurationData Nodes
- NonNodeData section now contains non-node related info
> Features Addition

- .codecov.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SharePointDSC.Reverse.ps1
- Tests/TestHarness.psm1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/27)
> 1.9.0.0 to PoShGallery

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/28)
> Preview 2.0 back into Master

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/32)
> Fixes server loop and @

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/33)
> ServerRole Fix

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/34)
> PR October 12

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/36)
> Added the new -Azure switch to the code branch

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/37)
> Fix for SPTimerJobState

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/38)
> Fixes for 2.0.0.0 Release

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/39)
> Merging version 2.0.0.0

- README.md
Restructured the readme and added a comment that one needs to log on to the SharePoint farm using the Farm Admin account to make it work. As discussed in https://github.com/Microsoft/SharePointDSC.Reverse/issues/41.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/42)
> Restructured the readme

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/43)
> Ready for 2.1.0.0

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/44)
> Fix for AuditingEnabled and ServerRole

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/46)
> Aligned with SPDSC 2.2.0.0

- README.md
- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/47)
> Prep for 2.3.0.0 and SPMMS fix for langs

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/49)
> Verbose for timer

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/50)
> Changed config names

- .MetaTestOptIn.json
- .markdownlint.json
- SharePointDSC.Reverse.ps1
- Tests/TestHarness.psm1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/51)
> AppVeyor Integration

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/53)
> Prep for 2.3.0.0 release

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/54)
> Merge 2.5.0.2

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/55)
> Fixed multiline Site and Web Description

- SharePointDSC.Reverse.ps1
Fixed issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/56)
> Fix issue with language for SPConfig

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/58)
> Fixes and Improvements

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/61)
> Improved StandAlone Extraction and Support for Web based results source

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/63)
> Major UI Upgrade

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/68)
> Upstream Merge

- SharePointDSC.Reverse.ps1
Fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/70)
> WebApp level fixes

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/72)
> Fix for SPServiceInstance

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/73)
> Aligned Default Extraction Mode with default GUI values

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/78)
> Release 3.3.0.0

- SharePointDSC.Reverse.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/sharepointdsc.reverse/82)
> Additional Fixes

- SharePointDSC.Reverse.ps1
> Multiple Fixes
